[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "https://www.rampit.xyz/*"
  to = "https://rampit.xyz/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
